---
# tasks file for win_service_config
#
- name: Install Windows package
  win_chocolatey:
    name: "{{ package_name }}"
    params: "{{ parameters }}"
    state: latest
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
- name: Start Windows service
  win_service:
    name: "{{ service_name }}"
    state: started
    start_mode: auto
    when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"  
- name: Add firewall rule
  win_firewall_rule:
    name: "{{ service_name }}"
    localport: "{{ local_port }}"
    action: allow
    direction: in
    protocol: "{{ protocol_name }}"
    state: present
    enabled: yes
